name: Build Folia

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Build Folia
        run: |
          ./gradlew applyPatches
          ./gradlew build

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: folia-jar
          path: build/libs/folia-paperclip-*.jar
